name: create verticals for noske

on: 
  # push:
  workflow_dispatch:
  # repository_dispatch:

jobs:
  create_noske:
    name: create verticals
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: github-pages
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    # - name: fetch data
    #   run: | 
    #     ./shellscripts/fetch_editions.sh
    # - name: Install Saxon, Ant and Python
    #   run: |
    #     apt-get update && apt-get install openjdk-11-jre-headless -y --no-install-recommend
    #     ./shellscripts/dl_saxon.sh 
    #     pip install -r ./pyscripts/requirements.txt
    # - name: tokenize xml
    #   run: |
    #     ant
    - name: mk verticals
      run: |
        python pyscripts/mk_verticals.py
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: created new verticals
