name: crate noske index & publish container
on:
  workflow_dispatch: {}

jobs:
  noske_index:
    name: Build Noske Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tags based on git data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/bundesverfassung-oesterreich/bv-noske/b-vg
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{sha}}
      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build and push to ghcr.io      
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nosketchengine/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
  
  _3:
    needs: [noske_index]
    uses: bundesverfassung-oesterreich/gl-autodevops-minimal-port/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      DOCKER_TAG: "ghcr.io/bundesverfassung-oesterreich/bv-noske/b-vg:latest"
      APP_NAME: "b-vg"
      APP_ROOT: "/"
      POSTGRES_ENABLED: false
      environment: "${{ github.ref_name }}"
      default_port: "8080"
